questions = {'1': {'question': '1: Why was Buddy mad after he came inside from going potty?'},
'2': {'question': '2: Where is candy?'},
'3': {'question': '3: Where is buddy employed?'},
'4': {'question': '4: When does candy enjoy moving?'},
'5': {'question': '5: Why did buddy start barking?'},
'6': {'question': '6: what number is after 6?'}}

answers = {"1": {"choice1": "A: Candy went inside first",
"choice2": "B: He didn't get a treat",
"choice3": "C: it was raining",
"choice4": "D: he got a treat",
"correct": "B"},
"2": {"choice1": "A: Outside",
"choice2": "B: In the basement",
"choice3": "C: Sleeping",
"choice4": "D: Exercising",
"correct": "C"},
"3": {"choice1": "A: The circus",
"choice2": "B: The library",
"choice3": "C: Sports clips",
"choice4": "D: He isn't",
"correct": "A"},
"4": {"choice1": "A: At the waterpark",
"choice2": "B: When she is forced to get up",
"choice3": "C: She doesn't",
"choice4": "D: To get a treat",
"correct": "D"},
"5": {"choice1": "A: He heard another dog bark",
"choice2": "B: Just to be annoying",
"choice3": "C: He wanted a treat",
"choice4": "D: Buddy would never bark",
"correct": "B"},
"6": {"choice1": "A: 3",
"choice2": "B: 4",
"choice3": "C: 5",
"choice4": "D: 7",
"correct": "D"}}
