questions = {'1': {'question': 'What is the capital of our country?'},
'2': {'question': 'How many limbs does a human have?'},
'3': {'question': 'How many calories should a person have in a day?'},
'4': {'question': 'What is this coded in?'},
'5': {'question': 'Whats the capital of our State?'}}

# qa = {"question": {"q_no": "1"}, {"question": "What is the capital of our country?"},
# {"answers": "choice1": "A: Chicago",
# "choice2": "B: Washington State",
# "choice3": "C: San Francisco",
# "choice4": "D: Washington D.C.",
# "correct": "D: Washington D.C."}

answers = {"1": {"choice1": "A: Chicago",
"choice2": "B: Washington State",
"choice3": "C: San Francisco",
"choice4": "D: Washington D.C.",
"correct": "D: Washington D.C."},
"2": {"choice1": "A: 35",
"choice2": "B: 2",
"choice3": "C: 6",
"choice4": "D: 4",
"correct": "D: 4"},
"3": {"choice1": "2322",
"choice2": "1000",
"choice3": "2000",
"choice4": "24000",
"correct": "2000"},
"4": {"choice1": "Snake",
"choice2": "Python",
"choice3": "Lizard",
"choice4": "Dog",
"correct": "Python"},
"5": {"choice1": "Chicago",
"choice2": "Springfield",
"choice3": "Des Plains",
"choice4": "Skokie",
"correct": "Springfield"}}
