questions = {'1': {'question': '1: What is the capital of our country?'},
'2': {'question': '2: How many limbs does a human have?'},
'3': {'question': '3: How many calories should a person have in a day?'},
'4': {'question': '4: What is this coded in?'},
'5': {'question': '5: Whats the capital of our State?'}}

# qa = {"question": {"q_no": "1"}, {"question": "What is the capital of our country?"},
# {"answers": "choice1": "A: Chicago",
# "choice2": "B: Washington State",
# "choice3": "C: San Francisco",
# "choice4": "D: Washington D.C.",
# "correct": "D: Washington D.C."}

answers = {"1": {"choice1": "A: Chicago",
"choice2": "B: Washington State",
"choice3": "C: San Francisco",
"choice4": "D: Washington D.C.",
"correct": "D"},
"2": {"choice1": "A: 35",
"choice2": "B: 2",
"choice3": "C: 6",
"choice4": "D: 4",
"correct": "D"},
"3": {"choice1": "A: 2322",
"choice2": "B: 1000",
"choice3": "C: 2000",
"choice4": "D: 24000",
"correct": "C"},
"4": {"choice1": "A: Snake",
"choice2": "B: Python",
"choice3": "C: Lizard",
"choice4": "D: Dog",
"correct": "B"},
"5": {"choice1": "A: Chicago",
"choice2": "B: Springfield",
"choice3": "C: Des Plains",
"choice4": "D: Skokie",
"correct": "B"}}
